@include('layouts.header')

<section class="relative isolate overflow-hidden bg-slate-900">
    <div class="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-900/85 to-slate-900/65"></div>
    <div class="relative mx-auto flex max-w-5xl flex-col gap-6 px-6 py-16 sm:py-20">
        <p class="text-xs font-semibold uppercase tracking-[0.35em] text-rose-300">CV Verification</p>
        <h1 class="text-3xl font-semibold text-white sm:text-4xl">Verification Failed</h1>
        <p class="text-lg text-slate-200 sm:text-xl">We couldn’t match the supplied verification code to any CV stored on ProSnap.</p>
    </div>
</section>

<main class="bg-slate-100">
    <div class="px-4 py-12 sm:px-6 lg:px-8">
        <div class="mx-auto max-w-4xl">
            <div class="rounded-2xl bg-white shadow-2xl">
                <div class="border-b border-rose-200 bg-gradient-to-r from-rose-600 to-amber-600 px-6 py-5 sm:px-8">
                    <div class="flex flex-col gap-2 text-white">
                        <h2 class="text-2xl font-semibold">No matching record found</h2>
                        <p class="text-sm text-rose-100">The code may be mistyped, the document revoked, or it was never generated by this platform.</p>
                    </div>
                </div>

                <div class="space-y-8 px-6 py-8 sm:px-8">
                    @isset($attemptedHash)
                        <div class="rounded-xl border border-rose-200 bg-rose-50 p-5">
                            <h3 class="text-sm font-semibold uppercase tracking-wide text-rose-700">Attempted verification ID</h3>
                            <p class="mt-3 break-all font-mono text-xs text-rose-900">{{ strtoupper($attemptedHash) }}</p>
                            <p class="mt-3 text-sm text-rose-800">Double-check the code from the CV footer, the verification badge, or the link shared by the candidate.</p>
                        </div>
                    @endisset

                    <section class="rounded-xl border border-slate-200 bg-slate-50 p-6">
                        <h3 class="text-base font-semibold text-slate-900">How to recover</h3>
                        <ol class="mt-3 list-decimal space-y-2 pl-5 text-sm text-slate-700">
                            <li>Ask the candidate to resend the verification link or regenerate their CV from the ProSnap dashboard.</li>
                            <li>Ensure the verification URL hasn’t been truncated when copying from email or messaging tools.</li>
                            <li>If this should be a valid document, confirm with the candidate that the version hasn’t been withdrawn.</li>
                        </ol>
                        <p class="mt-4 text-xs text-slate-500">Re-running verification with a new link does not require logging in and helps prevent tampered CVs from circulating.</p>
                    </section>

                    <div class="rounded-xl border border-amber-200 bg-amber-50 p-5">
                        <h3 class="text-sm font-semibold text-amber-700">Why we verify</h3>
                        <p class="mt-2 text-sm text-amber-900">Verification adds an optional trust layer so employers can check that a CV originated from ProSnap without manual follow-up. Candidates retain control—old versions can be deleted, and new ones produce fresh verification IDs.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@include('layouts.footer')
